### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by r3comp1le** [iSIGHTPartners/macaroni_server#1]
What if behind a corpo proxy?

**Comment by r3comp1le** [comment]
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'ubuntu/trusty64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
The box 'ubuntu/trusty32' could not be found or could not be accessed in the remote catalog. If this is a private box on HashiCorp's Atlas, please verify you're logged in via `vagrant login`. Also, please double-check the name. The expanded URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/ubuntu/trusty64"]
Error: Couldn't resolve host 'atlas.hashicorp.com'

**Comment by r3comp1le** [comment]
vagrant plugin install vagrant-proxyconf

**Comment by nms84** [comment]
Merged your pull request, thank you for the contribution :)
